In [17]:
import numpy as np

# circularly shift everything by a certain number of spaces clockwise
X = np.matrix('1 2 3 4; 5 6 7 8; 9 10 11 12')
print X
# circular shift by axis 1 (note this is the matlab default, "sideways counterclockwise")
Y = np.roll(X, 2, axis=1)
print Y

A = np.matrix('1 2 3 4 5 6 7 8 9 10')
print A
B = np.rot90(A,k=3);
print B

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 3  4  1  2]
 [ 7  8  5  6]
 [11 12  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
